### ISSUE TITLE
AttributeError: can't set attribute 'sd_model'

### ISSUE THREAD

**Issue by Gamekiller48** [Gerschel/xyz-plot-grid#10]
"Checkpoint name" doesn't seem to work as a setting for an axis, following some recent update to the webui.

Steps to replicate:
Set Seed as X axis, Steps as Y axis and Checkpoint Name as Z axis, enter appropriate values.

`X/Y/Z plot will create 8 images on a 2x2x2 grid. (Total steps to process: 84)
Error completing request
Arguments: ('task(qgyrk7aa8edrg2c)', 'positive vibes', 'negative vibes', [], 25, 15, False, False, 1, 1, 7, 987654321.0, 0.0, 0, 0, 0, False, 832, 512, False, 0.4, 1.25, 'R-ESRGAN 2x+', 0, 0, 0, 4, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, False, False, False, False, '', 1, '', 0, '', True, False, False, 1, '1,2', 4, '10,11', 9, 'sd-v1-4, SDv1-5', True, True, False, 10, '', 0, '', True, False, False, '', False, False, False, False, 'Auto', 0.5, 1, '30', 'fixed', 1, '8', 'Lanczos', 1, 'mp4', 10.0, 0, '', True, 'Euler a', 0.95, 0.75, 'zero', 'pos', 'linear', 0.01, 0.0, 0.75, None, 'Positive', 0, ', ', 'Generate and always save', 32) {}
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 470, in run
    processed, grids_size = draw_xyz_grid(
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 234, in draw_xyz_grid
    processed:Processed = cell(x, y, z)
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 464, in cell
    z_opt.apply(pc, z, zs)
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 118, in apply_checkpoint
    p.sd_model = shared.sd_model
AttributeError: can't set attribute 'sd_model'
`

The error appears no matter whether the Checkpoint Name is abreviated, spelled out in its entirety, has checksum included or not.
A failure to find the correct Checkpoint (e.g. because of a typo) also causes a different error, so that's not it.

**Comment by Gamekiller48** [comment]
I just now pulled the most recent version of the webui [(commit cbfb463...)](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cbfb4632585415dc914aff8c44869d792fd64c24), now I receive an even longer error message:

```
X/Y/Z plot will create 8 images on a 2x2x2 grid. (Total steps to process: 160)
Loading weights [1e540f764a] from E:\stable-diffusion-webui\models\Stable-diffusion\sd-v1-4-fp32.safetensors
Applying xformers cross attention optimization.
Weights loaded in 3.8s.
Loading weights [5f46236a72] from cache
Applying xformers cross attention optimization.
Weights loaded in 1.0s.
Error completing request
Arguments: ('task(ogc2jiagg04axql)', 'positive vibes', 'negative vibes', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 4, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, False, False, False, False, '', 1, '', 0, '', True, False, False, 1, '10,11', 5, '10,11', 9, 'sd-v1-4, SDv1-5', True, True, False, 10, '', 0, '', True, False, False, '', False, False, False, False, 'Auto', 0.5, 1, '30', 'fixed', 1, '8', 'Lanczos', 1, 'mp4', 10.0, 0, '', True, 'Euler a', 0.95, 0.75, 'zero', 'pos', 'linear', 0.01, 0.0, 0.75, None, 'Positive', 0, ', ', 'Generate and always save', 32) {}
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 470, in run
    processed, grids_size = draw_xyz_grid(
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 234, in draw_xyz_grid
    processed:Processed = cell(x, y, z)
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 464, in cell
    z_opt.apply(pc, z, zs)
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 118, in apply_checkpoint
    p.sd_model = shared.sd_model
AttributeError: can't set attribute 'sd_model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 468, in run
    with SharedSettingsStackHelper():
  File "E:\stable-diffusion-webui\scripts\xyz_plot_grid.py", line 294, in __exit__
    hypernetwork.apply_strength()
AttributeError: module 'modules.hypernetworks.hypernetwork' has no attribute 'apply_strength'
```

**Comment by Gerschel** [comment]
It's going to be some hours. I have several extensions that are giving me problems now. This one is the furthest behind. I'll try to catch it up entirely.
